### ISSUE TITLE
(Optionally) reduce strictness of "booleans everywhere" rule

### ISSUE THREAD

**Issue by rainbow-alex** [phpstan/phpstan-strict-rules#73]
> Require booleans in `if`, `elseif`, ternary operator, after `!`, and on both sides of `&&` and `||`.

I get what this rule is trying to accomplish, but imho truthiness is pretty intuitive and unsurprising for most types. For example, I don't see anything wrong with doing an `if ($something)` where `$something` is known to be `Something|null`.

The obvious and afaik only exception would be strings, where e.g. `"0"` is falsey... So I suggest to change this rule to:

> Forbid strings in `if`, `elseif`, ternary operator, after `!`, and on both sides of `&&` and `||`.

Either by default or opt-in via a parameter.

**Comment by ondrejmirtes** [comment]
I stay firmly behind this rule. Cast to boolean can be safe for some narrow set of types like `array` or `Something|null`, but without requiring booleans in conditions everywhere across the board, the developer has to always think about "is this safe or should I use a more explicit comparison?". PHPStan philosophy is "don't make me think"

I can think of these examples which are hard to reason about without more explicit comparison:

* `array|null` - did the user think about an empty array or also the null?
* `Something|array|null` - what did the user mean?

So instead of trying to come up with some rules (for this rule), it's better and more safe to always require a comparison.

**Comment by rainbow-alex** [comment]
Yeah, that's a good point. I avoid mixed types like the plague, so it didn't occur to me. But as a general rule the current behavior is better.
